stages:
  - test
variables:

UnitTestVue:
  image: node:alpine
  stage: test
  before_script:
    - yarn install
  when: on_success
  script:
    - yarn test

UnitTestDjango:
  image: python:3.6
  stage: test
  before_script:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
  when: on_success
  script:
    - python3 run_lint.py
    - coverage run --include='backend/api/*' manage.py test
    - coverage report -m
