# Generated by Django 3.0.4 on 2020-04-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenDosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'asisten dosen',
                'verbose_name_plural': 'asisten dosen',
            },
        ),
    ]
