# Generated by Django 3.0.4 on 2020-04-28 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemesan', models.CharField(max_length=64)),
                ('npm_pemesan', models.CharField(max_length=10)),
                ('waktu_pemesanan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pesanan',
                'verbose_name_plural': 'pesanan',
            },
        ),
        migrations.CreateModel(
            name='StatusBayar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'status bayar',
                'verbose_name_plural': 'status bayar',
            },
        ),
        migrations.CreateModel(
            name='StatusSurat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'status surat',
                'verbose_name_plural': 'status surat',
            },
        ),
        migrations.CreateModel(
            name='SuratAkademik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_dokumen', models.CharField(max_length=64, unique=True)),
                ('harga_mahasiswa', models.PositiveIntegerField(default=0)),
                ('harga_alumni', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'surat akademik',
                'verbose_name_plural': 'surat akademik',
            },
        ),
        migrations.CreateModel(
            name='PesananSuratAkademik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permohonan_surat.Pesanan')),
                ('status_surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permohonan_surat.StatusSurat')),
                ('surat_akademik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permohonan_surat.SuratAkademik')),
            ],
            options={
                'verbose_name': 'pesanan surat akademik',
                'verbose_name_plural': 'pesanan surat akademik',
            },
        ),
        migrations.AddField(
            model_name='pesanan',
            name='status_bayar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permohonan_surat.StatusBayar'),
        ),
    ]
