# Generated by Django 3.0.4 on 2020-04-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permohonan_surat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanansuratakademik',
            name='jumlah',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='pesanansuratakademik',
            constraint=models.UniqueConstraint(fields=('pesanan', 'surat_akademik'), name='Unique combination pesanan and surat_akademik'),
        ),
    ]
