# Generated by Django 3.0.4 on 2020-04-29 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permohonan_surat', '0003_auto_20200429_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanansuratakademik',
            name='jumlah',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
