# Generated by Django 3.0.4 on 2020-05-03 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permohonan_surat', '0004_auto_20200429_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='pemesan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
