# Generated by Django 3.0.4 on 2020-05-10 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permohonan_surat', '0005_pesanan_pemesan'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKaryaAkhir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuratKaryaAkhir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataKaryaAkhir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peminatan_mahasiswa', models.CharField(max_length=100)),
                ('sks_diperoleh', models.PositiveIntegerField()),
                ('pembimbing', models.CharField(max_length=70)),
                ('pembimbing_pendamping', models.CharField(blank=True, max_length=70)),
                ('judul_karya_id', models.TextField()),
                ('judul_karya_en', models.TextField(blank=True)),
                ('jenis_karya_akhir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permohonan_surat.JenisKaryaAkhir')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
