# Generated by Django 3.0.4 on 2020-05-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permohonan_surat', '0006_datakaryaakhir_jeniskaryaakhir_programstudi_suratkaryaakhir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datakaryaakhir',
            name='jenis_karya_akhir',
        ),
        migrations.RemoveField(
            model_name='datakaryaakhir',
            name='mahasiswa',
        ),
        migrations.DeleteModel(
            name='ProgramStudi',
        ),
        migrations.DeleteModel(
            name='SuratKaryaAkhir',
        ),
        migrations.DeleteModel(
            name='DataKaryaAkhir',
        ),
        migrations.DeleteModel(
            name='JenisKaryaAkhir',
        ),
    ]
