# Generated by Django 3.0.5 on 2020-06-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karya_akhir', '0003_auto_20200511_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='datakaryaakhir',
            name='ipk',
            field=models.FloatField(),
            preserve_default=False,
        ),
    ]
