# Generated by Django 3.0.3 on 2020-02-27 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPengumuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Ruang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Sesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPengumuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('nama_pembuat', models.CharField(max_length=32)),
                ('nama_dosen', models.CharField(max_length=32)),
                ('komentar', models.CharField(max_length=255)),
                ('jenis_pengumuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengumuman.JenisPengumuman')),
                ('nama_mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengumuman.MataKuliah')),
                ('nama_ruang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengumuman.Ruang')),
                ('nama_sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengumuman.Sesi')),
                ('nama_status_pengumuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengumuman.StatusPengumuman')),
            ],
        ),
    ]
