# Generated by Django 3.0.3 on 2020-03-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='npm',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
