# Generated by Django 3.0.3 on 2020-03-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0002_auto_20200227_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenispengumuman',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ruang',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sesi',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='statuspengumuman',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
