# Generated by Django 3.0.3 on 2020-03-01 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0003_auto_20200301_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='tanggal_kelas',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
