# Generated by Django 3.0.3 on 2020-03-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0004_pengumuman_tanggal_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='nama_asisten',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
