# Generated by Django 3.0.3 on 2020-03-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0004_auto_20200301_1140'),
        ('pengumuman', '0005_pengumuman_nama_asisten'),
    ]

    operations = [
    ]
