# Generated by Django 3.0.3 on 2020-03-03 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0006_merge_20200302_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengumuman',
            name='nama_pembuat',
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='pembuat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
