# Generated by Django 3.0.4 on 2020-03-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0008_auto_20200303_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='npm',
        ),
    ]
