# Generated by Django 3.0.4 on 2020-03-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0010_auto_20200319_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
