# Generated by Django 3.0.4 on 2020-03-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0011_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jenispengumuman',
            options={'verbose_name': 'jenis pengumuman', 'verbose_name_plural': 'jenis pengumuman'},
        ),
        migrations.AlterModelOptions(
            name='matakuliah',
            options={'verbose_name': 'mata kuliah', 'verbose_name_plural': 'mata kuliah'},
        ),
        migrations.AlterModelOptions(
            name='pengumuman',
            options={'verbose_name': 'pengumuman', 'verbose_name_plural': 'pengumuman'},
        ),
        migrations.AlterModelOptions(
            name='ruang',
            options={'verbose_name': 'ruang', 'verbose_name_plural': 'ruang'},
        ),
        migrations.AlterModelOptions(
            name='sesi',
            options={'verbose_name': 'sesi', 'verbose_name_plural': 'sesi'},
        ),
        migrations.AlterModelOptions(
            name='statuspengumuman',
            options={'verbose_name': 'status pengumuman', 'verbose_name_plural': 'status pengumuman'},
        ),
    ]
