# Generated by Django 3.0.4 on 2020-03-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_ui', '0003_auto_20200319_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'admin', 'verbose_name_plural': 'admin'},
        ),
        migrations.AlterModelOptions(
            name='asistendosen',
            options={'verbose_name': 'asisten dosen', 'verbose_name_plural': 'asisten dosen'},
        ),
        migrations.AddField(
            model_name='profile',
            name='nip',
            field=models.CharField(blank=True, max_length=10, verbose_name='Nomor Induk Pegawai'),
        ),
    ]
