# Generated by Django 3.0.4 on 2020-04-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso_ui', '0004_auto_20200325_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsistenDosen',
        ),
    ]
