# Generated by Django 3.0.4 on 2020-04-15 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso_ui', '0005_delete_admin'),
        ('sso_ui', '0005_delete_asistendosen'),
    ]

    operations = [
    ]
