# Generated by Django 3.0.4 on 2020-04-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_ui', '0006_merge_20200415_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
