# Generated by Django 3.0.4 on 2020-04-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso_ui', '0007_user_is_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_blocked',
            new_name='blocked',
        ),
    ]
